[workspace]
authors = ["Willi Rath <wrath@geomar.de>"]
channels = ["conda-forge"]
name = "preproc"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
xarray = ">=2026.1.0,<2027"
pandas = ">=3.0.0,<4"
geopandas = ">=1.1.2,<2"
dask = ">=2026.1.2,<2027"
matplotlib = ">=3.10.8,<4"
netcdf4 = ">=1.7,<2"
pydap = ">=3.5,<4"
jupyter = ">=1.1,<2"
jupyterlab = ">=4.3,<5"
papermill = ">=2.6,<3"
tqdm = ">=4.67,<5"
copernicusmarine = ">=2.3,<3"
