apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /tmp/kompose convert -f ../docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "5173"
      port: 5173
      targetPort: 80
  selector:
    io.kompose.service: nginx
