apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "5173"
      port: 5173
      targetPort: 8080
  selector:
    io.kompose.service: nginx
