apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ostrea-api
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
spec:
  host: localhost
  path: /api
  to:
    kind: Service
    name: api
  port:
    targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ostrea-frontend
spec:
  host: localhost
  to:
    kind: Service
    name: frontend
  port:
    targetPort: 8080
