{{- if .Values.openshift }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ostrea-api
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
spec:
{{- if .Values.host }}
  host: {{ .Values.host }}
{{- end }}
  path: /api
  to:
    kind: Service
    name: api
  port:
    targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ostrea-frontend
spec:
{{- if .Values.host }}
  host: {{ .Values.host }}
{{- end }}
  to:
    kind: Service
    name: frontend
  port:
    targetPort: 8080
{{- end }}
